version: "3.8"
services:
  mongo:
    image: mongo:6.0
    container_name: spells-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: spellsdb
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  api:
    build: .
    container_name: spell-api
    restart: unless-stopped
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - mongo

volumes:
  mongo-data:
